export { default as SearchIcon } from './SearchIcon';
export { default as ShopCartIcon } from './ShopCartIcon';
export { default as LoginIcon } from './LoginIcon';
export { default as LocationMarkerIcon } from './LocationMarkerIcon';
export { default as InstagramIcon } from './InstagramIcon';
export { default as VkIcon } from './VkIcon';
export { default as CloseIcon } from './CloseIcon';
export { default as CheckedIcon } from './CheckedIcon';
export { default as FailIcon } from './FailIcon';
